### PR TITLE
The single most important PR

### PR DESCRIPTION
**Pull request by ItsDrike**

### CODE REVIEW

**Review by UlisseMini — COMMENTED** [review]
Looks good, perhaps adding a `if random.randint(0, 100) == 42` redirect rickroll in `/` would be a good addition

**Comment by ItsDrike** [comment]
> Looks good, perhaps adding a `if random.randint(0, 100) == 42` redirect rickroll in `/` would be a good addition

It would be interesting, but if someone trips that the first time, he might think that's all that site does and that it's not actually the site of the church, but instead a clever rickroll only, so I probably wouldn't do this

**Review by UlisseMini — APPROVED** [review]
LGTM :shipit:

**Review by spencerpogo — APPROVED** [review]
:shipit:

**Pull request merged**
